/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface MedicineAuthInterface extends utils.Interface {
  functions: {
    "approveManufacturer(address)": FunctionFragment;
    "getAllRequests()": FunctionFragment;
    "manufacturers(address)": FunctionFragment;
    "medicineExists(string)": FunctionFragment;
    "owner()": FunctionFragment;
    "registerMedicine(string,string,string,string,string)": FunctionFragment;
    "rejectManufacturer(address)": FunctionFragment;
    "requestAccess(string)": FunctionFragment;
    "requestedManufacturers(uint256)": FunctionFragment;
    "verifyMedicine(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "approveManufacturer"
      | "getAllRequests"
      | "manufacturers"
      | "medicineExists"
      | "owner"
      | "registerMedicine"
      | "rejectManufacturer"
      | "requestAccess"
      | "requestedManufacturers"
      | "verifyMedicine"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveManufacturer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "manufacturers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "medicineExists",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMedicine",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectManufacturer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAccess",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "requestedManufacturers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMedicine",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manufacturers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "medicineExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMedicine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestedManufacturers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMedicine",
    data: BytesLike
  ): Result;

  events: {
    "MedicineRegistered(string,string,string,string,string,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MedicineRegistered"): EventFragment;
}

export interface MedicineRegisteredEventObject {
  id: string;
  name: string;
  manufacturer: string;
  mfgDate: string;
  expiryDate: string;
  registeredBy: string;
}
export type MedicineRegisteredEvent = TypedEvent<
  [string, string, string, string, string, string],
  MedicineRegisteredEventObject
>;

export type MedicineRegisteredEventFilter =
  TypedEventFilter<MedicineRegisteredEvent>;

export interface MedicineAuth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MedicineAuthInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllRequests(overrides?: CallOverrides): Promise<[string[]]>;

    manufacturers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, boolean] & {
        name: string;
        approved: boolean;
        requested: boolean;
      }
    >;

    medicineExists(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    registerMedicine(
      _id: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _manufacturer: PromiseOrValue<string>,
      _mfgDate: PromiseOrValue<string>,
      _expiryDate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rejectManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestAccess(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestedManufacturers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    verifyMedicine(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, boolean] & {
        id: string;
        name: string;
        manufacturer: string;
        mfgDate: string;
        expiryDate: string;
        exists: boolean;
      }
    >;
  };

  approveManufacturer(
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllRequests(overrides?: CallOverrides): Promise<string[]>;

  manufacturers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, boolean, boolean] & {
      name: string;
      approved: boolean;
      requested: boolean;
    }
  >;

  medicineExists(
    _id: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  registerMedicine(
    _id: PromiseOrValue<string>,
    _name: PromiseOrValue<string>,
    _manufacturer: PromiseOrValue<string>,
    _mfgDate: PromiseOrValue<string>,
    _expiryDate: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rejectManufacturer(
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestAccess(
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestedManufacturers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  verifyMedicine(
    _id: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string, boolean] & {
      id: string;
      name: string;
      manufacturer: string;
      mfgDate: string;
      expiryDate: string;
      exists: boolean;
    }
  >;

  callStatic: {
    approveManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllRequests(overrides?: CallOverrides): Promise<string[]>;

    manufacturers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, boolean] & {
        name: string;
        approved: boolean;
        requested: boolean;
      }
    >;

    medicineExists(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    registerMedicine(
      _id: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _manufacturer: PromiseOrValue<string>,
      _mfgDate: PromiseOrValue<string>,
      _expiryDate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    rejectManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    requestAccess(
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    requestedManufacturers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    verifyMedicine(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, boolean] & {
        id: string;
        name: string;
        manufacturer: string;
        mfgDate: string;
        expiryDate: string;
        exists: boolean;
      }
    >;
  };

  filters: {
    "MedicineRegistered(string,string,string,string,string,address)"(
      id?: null,
      name?: null,
      manufacturer?: null,
      mfgDate?: null,
      expiryDate?: null,
      registeredBy?: null
    ): MedicineRegisteredEventFilter;
    MedicineRegistered(
      id?: null,
      name?: null,
      manufacturer?: null,
      mfgDate?: null,
      expiryDate?: null,
      registeredBy?: null
    ): MedicineRegisteredEventFilter;
  };

  estimateGas: {
    approveManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllRequests(overrides?: CallOverrides): Promise<BigNumber>;

    manufacturers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    medicineExists(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    registerMedicine(
      _id: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _manufacturer: PromiseOrValue<string>,
      _mfgDate: PromiseOrValue<string>,
      _expiryDate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rejectManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestAccess(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestedManufacturers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyMedicine(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllRequests(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    manufacturers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    medicineExists(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerMedicine(
      _id: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _manufacturer: PromiseOrValue<string>,
      _mfgDate: PromiseOrValue<string>,
      _expiryDate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rejectManufacturer(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestAccess(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestedManufacturers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyMedicine(
      _id: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
